import type { Metadata } from "next";
import LegalShell from "../legal-shell";

export const metadata: Metadata = { title: "AGB | AB3D Swiss Design" };

export default function AgbPage() {
  return (
    <LegalShell title="Allgemeine Geschäftsbedingungen" intro="Regeln für AB3D 3D-Produkte, CAPPATEX Print-on-Demand und Creator Plans.">
      <section><h2>1. Geltungsbereich</h2><p>Diese AGB gelten für Angebote von AB3D Swiss Design in der Schweiz und in Liechtenstein: Kollektionsteile, individuell gestaltete 3D-Produkte, CAPPATEX Print-on-Demand-Produkte sowie digitale Nutzungs- und Abonnementleistungen.</p></section>
      <section><h2>2. AB3D Bestellung und Vertrag</h2><p>Produktauswahl und Warenkorb werden direkt auf der AB3D Website zusammengestellt. Für Lieferadresse, definitive Versandkosten und Zahlung wird anschliessend der sichere Shopify-Checkout geöffnet. Vor dem zahlungspflichtigen Abschluss können alle Angaben geprüft und korrigiert werden. Der Vertrag entsteht mit der im Checkout bezeichneten Bestellbestätigung, vorbehaltlich einer notwendigen technischen Machbarkeitsprüfung bei individuell gefertigten Produkten.</p></section>
      <section><h2>3. CAPPATEX Bestellung</h2><p>Bei CAPPATEX wird ein Design zunächst als Vorschau erstellt und auf einem gewählten Produkt platziert. Vor dem externen Bezahlvorgang werden Produkt, Variante, Menge und Richtpreis angezeigt. Der verbindliche Vertragsschluss und die Zahlung erfolgen nach den im Checkout angezeigten Angaben. Produktion beginnt erst nach erfolgreicher Zahlungsbestätigung und den vorgesehenen Prüfungen.</p></section>
      <section><h2>4. Preise und Versand</h2><p>Preise werden in Schweizer Franken angezeigt. Im AB3D Warenkorb beträgt der aktuelle Versandrichtwert CHF 9; ab CHF 80 Warenwert wird er mit CHF 0 berechnet. Massgeblich ist stets der unmittelbar vor Vertragsabschluss im Checkout angezeigte Gesamtpreis. Bei CAPPATEX gelten ebenfalls die im Checkout angezeigten Produkt-, Versand- und gegebenenfalls Abgabenbeträge.</p></section>
      <section><h2>5. Personalisierte und KI-gestützte Produkte</h2><p>Darstellungen auf dem Bildschirm sind Vorschauen. Farbe, Oberflächenbild, Position, Mass und kleinere Fertigungsspuren können material- und produktionsbedingt abweichen. KI-Ergebnisse sind nicht garantiert einzigartig. Wir dürfen technisch notwendige Anpassungen vornehmen, sofern Charakter und vereinbarter Zweck des Designs gewahrt bleiben.</p></section>
      <section><h2>6. Rechte an Eingaben</h2><p>Wer Texte, Fotos, Grafiken, Logos oder Modelle übermittelt, bestätigt, über die notwendigen Rechte und Einwilligungen zu verfügen. Inhalte dürfen keine Rechte Dritter verletzen, insbesondere keine Marken-, Urheber-, Persönlichkeits- oder Designrechte. Unzulässige, gefährliche oder rechtswidrige Aufträge dürfen wir ablehnen.</p></section>
      <section><h2>7. Creator Plans und Tokens</h2><p>Tokens ermöglichen die jeweils beschriebene Nutzung der Kreativwerkzeuge; sie sind kein Zahlungsmittel und haben keinen Barauszahlungswert. Physische Produktpreise und Versand sind nicht in einem Token- oder Creator-Plan enthalten. Dateidownloads stehen nur im jeweils ausgewiesenen Plan zur Verfügung.</p><p>Creator Plans können derzeit unverbindlich angefragt, aber noch nicht kostenpflichtig abgeschlossen werden. Eine Anfrage löst weder eine Zahlung noch eine automatische Verlängerung aus. Sobald bezahlte Pläne angeboten werden, werden Preis, Leistung, Laufzeit, Verlängerung, Kündigung, Token-Gültigkeit und Rückerstattungsbedingungen vor dem zahlungspflichtigen Abschluss vollständig angezeigt.</p></section>
      <section><h2>8. Prüfung, Ablehnung und Stornierung</h2><p>Individuelle Entwürfe können wegen fehlender Druckbarkeit, Sicherheitsrisiken, Rechtsverletzungen oder technischer Grenzen abgelehnt oder zur Anpassung zurückgegeben werden. Vor Produktionsbeginn kann eine Änderung angefragt werden; nach Produktionsbeginn sind Änderungen oder freiwillige Stornierungen personalisierter Produkte grundsätzlich nicht mehr möglich.</p></section>
      <section><h2>9. Mängel</h2><p>Produkte sind nach Erhalt zu prüfen. Transportschäden, falsche Artikel oder wesentliche Mängel sollen möglichst rasch mit Bestellreferenz und aussagekräftigen Fotos an <a href="mailto:hello@ab3d.ch">hello@ab3d.ch</a> gemeldet werden. Gesetzliche Gewährleistungsrechte bleiben vorbehalten. Normale 3D-Druck-Schichtlinien, geringfügige Farbabweichungen und vereinbarte handwerkliche Merkmale sind für sich allein kein Mangel.</p></section>
      <section><h2>10. Haftung</h2><p>Wir haften im Rahmen des zwingenden Rechts. Für Schäden durch zweckwidrige Nutzung, eigenmächtige Veränderung, ungeeignete Hitze-, Lebensmittel-, Wasser- oder elektrische Anwendung sowie missachtete Sicherheits- und Pflegehinweise ist die Haftung soweit gesetzlich zulässig ausgeschlossen.</p></section>
      <section><h2>11. Anwendbares Recht</h2><p>Es gilt schweizerisches Recht unter Vorbehalt zwingender Konsumentenschutzbestimmungen. Für Konsumentenstreitigkeiten bleiben die gesetzlich vorgesehenen Gerichtsstände, insbesondere am Wohnsitz der Konsumentin oder des Konsumenten, unberührt.</p></section>
      <section><h2>12. Stand</h2><p>Stand: 19. August 2026. Änderungen gelten nur für zukünftige Bestellungen und Leistungen; die jeweils einbezogene Fassung wird mit der Bestellung dokumentiert.</p></section>
    </LegalShell>
  );
}
